apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: openfaas-fn
spec:
  ports: 
  - port: 3306
    name: mysql
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql

  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: openfaas-fn
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      hostname: mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        ports:
        - containerPort: 3306
          name: mysql
