version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  init:
    lang: dockerfile
    handler: ./init
    image: localhost:5001/init:latest
    skip_build: true
  authenticate:
    lang: dockerfile
    handler: ./authenticate
    image: localhost:5001/authenticate:latest
    skip_build: true
    environment:
      OAUTH_SERVER: 'accounts.google.com'
  product-catalog-api:
    lang: dockerfile
    handler: ./product-catalog-api
    image: localhost:5001/product-catalog-api:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PRODUCT_CATEGORY_NAME: 'productCategory'
      TABLE_PRODUCT_CATALOG_NAME: 'productCatalog'
      TABLE_PRODUCT_PRICE_NAME: 'productPrice'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-catalog-builder:
    lang: dockerfile
    handler: ./product-catalog-builder
    image: localhost:5001/product-catalog-builder:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PRODUCT_CATEGORY_NAME: 'productCategory'
      TABLE_PRODUCT_CATALOG_NAME: 'productCatalog'
      TABLE_PRODUCT_PRICE_NAME: 'productPrice'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-photos-register:
    lang: dockerfile
    handler: ./product-photos-register
    image: localhost:5001/product-photos-register:latest
    skip_build: true
    environment:
      URL_AUTHENTICATE: 'http://gateway.openfaas:8080/function/authenticate'
      DBNAME: 'helloRetail'
      TABLE_PHOTO_REGISTRATIONS_NAME: 'photoRegistrationTable'
      ASSIGNMENTS_PER_REGISTRATION: 3
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-photos-assign:
    lang: dockerfile
    handler: ./product-photos-assign
    image: localhost:5001/product-photos-assign:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PHOTO_REGISTRATIONS_NAME: 'photoRegistrationTable'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-photos-message:
    lang: dockerfile
    handler: ./product-photos-message
    image: localhost:5001/product-photos-message:latest
    skip_build: true
  product-photos-record:
    lang: dockerfile
    handler: ./product-photos-record
    image: localhost:5001/product-photos-record:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PHOTO_ASSIGNMENTS_NAME: 'photoAssignmentTable'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-photos-receive:
    lang: dockerfile
    handler: ./product-photos-receive
    image: localhost:5001/product-photos-receive:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PHOTO_ASSIGNMENTS_NAME: 'photoAssignmentTable'
      TABLE_STORED_PHOTOS_NAME: 'storedPhotosTable'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-photos-success:
    lang: dockerfile
    handler: ./product-photos-success
    image: localhost:5001/product-photos-success:latest
    skip_build: true
  product-photos-report:
    lang: dockerfile
    handler: ./product-photos-report
    image: localhost:5001/product-photos-report:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PHOTO_ASSIGNMENTS_NAME: 'photoAssignmentTable'
      TABLE_PHOTO_REGISTRATIONS_NAME: 'photoRegistrationTable'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-purchase-authenticate:
    lang: dockerfile
    handler: ./product-purchase-authenticate
    image: localhost:5001/product-purchase-authenticate:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_AUTHENTICATION_NAME: 'authenticationName'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-purchase-get-price:
    lang: dockerfile
    handler: ./product-purchase-get-price
    image: localhost:5001/product-purchase-get-price:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PRODUCT_PRICE_NAME: 'productPrice'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-purchase-authorize-cc:
    lang: dockerfile
    handler: ./product-purchase-authorize-cc
    image: localhost:5001/product-purchase-authorize-cc:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_CREDIT_CARDS_NAME: 'creditCardsName'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-purchase-publish:
    lang: dockerfile
    handler: ./product-purchase-publish
    image: localhost:5001/product-purchase-publish:latest
    skip_build: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_CREDIT_CARDS_NAME: 'creditCardsName'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
  product-photos:
    lang: dockerfile
    handler: ./product-photos
    image: localhost:5001/product-photos:latest
    skip_build: true
    environment:
      URL_ASSIGN: 'http://gateway.openfaas:8080/function/product-photos-assign'
      URL_MESSAGE: 'http://gateway.openfaas:8080/function/product-photos-message'
      URL_RECORD: 'http://gateway.openfaas:8080/function/product-photos-record'
      URL_RECEIVE: 'http://gateway.openfaas:8080/function/product-photos-receive'
      URL_SUCCESS: 'http://gateway.openfaas:8080/function/product-photos-success'
      URL_REPORT: 'http://gateway.openfaas:8080/function/product-photos-report'
  product-purchase:
    lang: dockerfile
    handler: ./product-purchase
    image: localhost:5001/product-purchase:latest
    skip_build: true
    environment:
      URL_GETPRICE: 'http://gateway.openfaas:8080/function/product-purchase-get-price'
      URL_AUTHORIZECC: 'http://gateway.openfaas:8080/function/product-purchase-authorize-cc'
      URL_PUBLISH: 'http://gateway.openfaas:8080/function/product-purchase-publish'
